sudo: required
language: java
services:
- docker
env:
  global:
  - secure: oJyLvxIpWo737FfGJVwcXkd9f9/wGSrWj8K1wqce1w+9Ma+ueVaeBeOLsPJ1jVvluGRjGRcfCGyGaXKFGhFpNPPnTtAjuvYLHK7CJNMc535Is3yBi+dhbpY3JIursv8lYrXqoWIeQIA/sbVG8B3yXXxPgz4b5pZ2RBsAucZ6Cd4Dn1cyxL1A/xA1NkyHG8Q/1FiL3jTlGQQrlZXxZLTn+ytQqHk0nBXJXmw1E+k8UlnAP/YsZ1IiIG7IP3gf1KnVfxUpa6f01iR0uTYbSsUQsIM1qO4r9yDCQlKeBALEnutX99oBjjjCDeIXaLEE9J/1H0zFsqRPXvXs41MdSQ2WWVf3MqQtxkpCCp0ZHVWC7JAMhIYSM/mvySSsKJQFKVkKlkarc1+zDjGo4Csf1P17fNQYmjCXrUAC2OeZU5zGckFXNh24AVXCyn2oEefOJGxXqv9V7V4LOX53FyFQULRe1p902u2EhHayAAMBnqBS4oE8JrArvmcO2/wHPm6bku8fb5uB0I3X+j7Ow9+Qd3Kvp7sOAyTZS1OhEiVeF+tayToXk0t7ND56cC8WuXO3Hd5zLLxoum/VFuFytXoJmYtb4VubWXh5uewM0atEbDZ9eeKU2AUVDVLOoTyZXP/W6g1hIFaWiWzl+3gitLHcVxuPgzrzcLLmGuGrHOOaCMV5aPU=
  - secure: MpVEp2/wCaX+2Ui3H8lApQLnaAqn2+LsanhIUe1BAvhfkUdrB1up/+3BoahLnFT1XTeCIGs30rT6zUscgerHCSV3DrDn6gsND/YbjslrkRzFMG628Gj6eCEhbpv47da1A30faHMQLx9ALo4hRw8k1RyR9KkjS2RTKC7MT2wYVC+7BJSPMmeWzwaH2pPg4l4HYrtuHSFPfqRdRvJA8GkAy78MfVWekWooeDLN3dI4a3NBJL5m+tNgqOFXL0qGrfJCcr4fcrzLwLKfBf7FN+R1/pOI8YFD1FB07ER2lsbv2RYdLd5ge3WDvzweMQlbM8Nr6MdC5wQR3Dgz/oVBsCuFiU/jcZxNQWY96F562HrE0ORgnJjbjfeP1YUIp6Hoi3RLXuuve7zCTKsBKKH+O+Pc3wLEDLXSQLVE1g3TAPzH8OjNm0ZmC8PbiTGYG5fcs5sneJ420kVRbJexXh4FJ7NhiSX80MsEMT8ftqDaYajH0lNCB4BJR1ji+Pb40ku1j5p/zEQShhbVRQNVx5dlaVXe6qzjf2Cg32edi+tkDZzUfpn1/h9fwju/cKD/6e8Ly0xHXXiexSZSrdv6q3ViMFRe0o/fnxneK7MhMvkA3yUnwc0kXsaoLBRJ6ZOYlLsdQNFFmgiapDvaVE5hCGGOvAlnfZFYJXK5G/+NztTEAsIE8b4=
  - secure: K2aOdcbpkfFKF/j1Oib1ViKfe1RgcRvmasXaSs/5skBEb9t5b6D5ceYqb1TxT6eHRdrGmXnYoPItUM7JZb2cOuHC0DnMyyqzjRFnMIxohAPdd5CLCw2x1Y3XyIqyU80KrCORLMW4E8/uzGQ93Eqk97h14ZT/YtvNkzqV/yTimxJszCgNuhWRRua6gnG+6+GTQ5FyTatqXrk/sqfC8LwZ66iQZZfr7yBzunn2Vp3N/PGLHHf/M56ZCJdxfCC2p9KfG41sbPGM924Srx9AsR2MyG8xisSb1Ztcy21aa8WL+iFwBb/RP4IBvhU6xpVsXgcULSQV9HgliKYqmBZoS6fF6AvJwsEyaIhHCvGIo0qEpdWeTicqDvsGOg3TfAWH9PCTg5WopHuehuBzBKIPOAYO78DbdV+NOsq1uYiLvyprx4CVcK+eKNKodY1Qvqn8MUp8EVqKvIJ4liXplYeYZUjjkhFd7TBx0sOhnZL+evhoJdW2mbU+LPV2VuBap3qs69X7vCrr1L9iM/GMVbkv2LhoXX17VBJjcv8J2aLX+sbYvvssrr/y00R5Mlz1vVF6gyVTjvnNfEbXmZ0JCHOguOnKSz5Z6LhoNnrJ6DPOlCmyZSxet45+Rx0idiEvqTXxhZUDXnE5X49GqL44B2ez3v0UzJrnUf4+Wuge3ySp4ZuO5/0=
script:
- mvn clean install -B
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -t acebook-millieandco .
- docker tag acebook-millieandco williampowell/acebook-millieandco:1.0-SNAPSHOT
- docker push williampowell/acebook-millieandco:1.0-SNAPSHOT

addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt

deploy:
  provider: script
  on:
    branch: docker-setup-again
